on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bcomnes/get-git-tag@v3.0.1
        id: tagName
          
      - run:
          echo "${{ steps.tagName.outputs.tag }}"
