name: Update Docker Compose

on:
  release:
    types: [published]
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yaml'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  update-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Get tag
      id: tag
      uses: devops-actions/action-get-tag@v1.0.1

    - name: Update Docker Compose
      run: |
        sed "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ steps.tag.outputs.tag }}/g" docker-compose.yaml > docker-compose.updated.yaml

    - name: Replace docker-compose.yaml with updated file
      run: mv docker-compose.updated.yaml docker-compose.yaml

    - name: Commit changes to docker-compose.yaml
      uses: test-room-7/action-update-file@v1
      with:
          file-path: ./docker-compose.yaml
          commit-msg: (bot) update docker-compose.yaml
          github-token: ${{ secrets.REPO }}