name: Update Docker Compose

on:
  release:
    types: [published]
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yaml'
      - '.github/workflows/**'

jobs:
  update-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Print release version
      run: 
        echo "${{ github.event.release.tag_name }}"

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO }}

    - name: Update Docker Compose
      run: |
        sed "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.event.release.tag_name }}/g" docker-compose.yaml > docker-compose.updated.yaml
        mv docker-compose.updated.yaml docker-compose.yaml

    - name: Commit&Push files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "update version in docker-compose"
        git push origin HEAD:main